'use strict';

module.exports =
    angular.module('maziaj', [
        //load extra external dependencies here, e.g.:
        'ui.bootstrap',
        'ngRoute',
        'infinite-scroll',
        'LocalStorageModule',
        //html templates in $templateCache generated by Gulp:
        require('../../../tmp/templates').name,
        //useful directives, filters, services shared across the app
        require('../common').name,
    ]).config(function ($routeProvider) {
        $routeProvider.when('/', {
            controller: 'galleryCtrl',
            templateUrl: 'views/gallery.html',
            reloadOnSearch: false
        }, true);
        $routeProvider.when('/chain/:id', {
            controller: 'chainCtrl',
            templateUrl: 'views/chain.html'
        }, true);
        $routeProvider.when('/play', {
            controller: 'playCtrl',
            templateUrl: 'views/play.html'
        }, true);
        $routeProvider.when('/profile', {
            controller: 'profileCtrl',
            templateUrl: 'views/profile.html'
        }, true);
        $routeProvider.otherwise({redirectTo: '/'});
    })
        .controller('chainCtrl', require('./chainCtrl'))
        .controller('galleryCtrl', require('./galleryCtrl'))
        .controller('menuCtrl', require('./menuCtrl'))
        .controller('playCtrl', require('./playCtrl'))
        .controller('profileCtrl', require('./profileCtrl'));
